import type { NextApiRequest, NextApiResponse } from 'next';
import { taskQueueService } from '../../services/taskQueueService';
import { agentService } from '../../services/agentService';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // DISABLED: Old task queue system - only ChatGPT collaborative tasks are allowed
  return res.status(410).json({ 
    error: 'This endpoint is disabled. Use collaborative task endpoints for ChatGPT-generated tasks.',
    message: 'Only collaborative tasks generated by ChatGPT are now supported.',
    alternatives: [
      'GET /api/subtasks/pending/[agentAddress] - Get pending subtasks',
      'POST /api/subtasks/[id]/execute - Execute subtask',
      'GET /api/master-tasks/ready/[agentAddress] - Get ready master tasks',
      'POST /api/master-tasks/[id]/process - Process master task'
    ]
  });
}
