import type { NextApiRequest, NextApiResponse } from 'next';
import { agentService, TaskCreationData } from '../../services/agentService';

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {

  // DISABLED: Old task system - only ChatGPT collaborative tasks are allowed
  return res.status(410).json({ 
    error: 'This endpoint is disabled. Use collaborative task endpoints for ChatGPT-generated tasks.',
    message: 'Only collaborative tasks generated by ChatGPT are now supported.',
    alternatives: [
      'POST /api/tasks/generate-collaborative - Generate collaborative tasks',
      'GET /api/tasks/collaborative-status - Get collaborative task status'
    ]
  });
}
